### ISSUE TITLE
[3.6.1] error TS2306: File 'node_modules/react-icons/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by wKovacs64** [react-icons/react-icons#230]
**Describe the bug**

Upon attempting to update react-icons from v3.6.0 to v3.6.1 in a Gatsby TypeScript project, I am met with the following error:
```
error TS2306: File '/root/project/node_modules/react-icons/index.d.ts' is not a module.
```
The line of code that triggers this build-time error is:
```ts
import { IconContext } from 'react-icons';
```

**Minimal sample repository**

Not minimal, but I first ran into it in https://github.com/wKovacs64/pwl/pull/55.

Let me know if a minimal reproduction would be more helpful and I will throw one together.

**Expected behavior**

I expected it to work as it did in v3.5.0.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - Device: Server (Circle CI container)
 - OS: Linux (Ubuntu)
 - Browser: N/A
 - Version: N/A

**Additional context**

I suspect this is a result of the module structure changes made in v3.6.0 beta, and it appears v3.6.0 was published using the old (v3.5.0) structure? See [v3.6.0](https://unpkg.com/react-icons@3.6.0/lib/) vs. [v3.6.1](https://unpkg.com/react-icons@3.6.1/lib/) on unpkg.

**Comment by deejaygeroso** [comment]
@wKovacs64 I have react-icons v3.2.2 and still the same issue

**Comment by deejaygeroso** [comment]
@wKovacs64 I guess you are right. But it's still worth checking.
I've been testing those version. Then I ended up downgrading to v3.4.0 as of now.

**Comment by deejaygeroso** [comment]
I tried it again this morning went and checkout my working branch then the error message shows up again on v3.4.0 and I realized might as well use a different package instead

**Comment by bsr203** [comment]
hi. I see `index.d.ts` is empty with just one comment

> // THIS FILE IS AUTO GENERATED

package version 
  "name": "react-icons",
  "version": "3.6.1",

I workaround by importing directly like

```
import { IconBaseProps } from 'react-icons/lib/esm';
```

**Comment by wKovacs64** [comment]
Any thoughts on this, @kamijin-fanta?

**Comment by nhsiehgit** [comment]
Also seeing this issue.
I've just untyped the module for now

**Comment by eutopian** [comment]
You can import directly from lib

`import { IconContext } from 'react-icons/lib';

seems like the `outDir` was changed here https://github.com/react-icons/react-icons/commit/97bf4190b0af0e8647dc8352d7664d9410c888ec#diff-42f7fc395ef36833bbad8a64787eea19R3

**Comment by exogen** [comment]
Looks like this is causing issues for non-TypeScript users as well. The issue is that the second `package.json` in `lib` approach, while interesting, is compatible with webpack's resolution algorithm but not Node's (or, it seems, TypeScript).

So if you do server side rendering and `import { IconContext } from 'react-icons'` it will fail during SSR, but work fine if you do it only in your webpack bundle.

**Comment by kamijin-fanta** [comment]
I will try to fix. please wait a moment.
Changes to package.json should fix it.

**Comment by kamijin-fanta** [comment]
please try react-icons@3.7.0.

**Comment by exogen** [comment]
Not sure about TypeScript, but the Node SSR case is still an issue on 3.7.0 – I can make a separate issue for that if it's preferable.

```console
$ node
> require('react-icons')
Error: Cannot find module 'react-icons'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

Could potentially be the cause of this too: https://github.com/react-icons/react-icons/issues/227

**Comment by Faeljc** [comment]
I managed to resolve this problem by adding the following snippet to the 'tsconfig.json' file:
`"moduleResolution": "node",`
